trigger:
  branches:
    include:
    - '*'
  tags:
    include:
    - '*'
pr: none
resources:
  repositories:
  - repository: PSModulePublisher
    type: github
    name: theohbrothers/PSModulePublisher
    endpoint: joeltimothyoh
    ref: refs/heads/dev-powershell
  - repository: PSRepositoryReleaseManager
    type: github
    name: theohbrothers/PSRepositoryReleaseManager
    endpoint: joeltimothyoh
    ref: refs/heads/dev

stages:
- stage: Build_Test_Publish
  displayName: Build, Test, Publish
  jobs:
  - job: windows_pwsh
    displayName: Windows-Pwsh
    pool:
      vmImage: windows-2019
    steps:
    - checkout: self
      submodules: recursive
    - template: templates/azure-pipelines/windows/pwsh/continuous-build.yml@PSModulePublisher
    - template: templates/azure-pipelines/windows/pwsh/publish.yml@PSModulePublisher
    - template: templates/azure-pipelines/run-release.yml@PSRepositoryReleaseManager
  - job: windows_powershell_5_1
    displayName: Windows-Powershell5.1
    pool:
      vmImage: windows-2019
    steps:
    - checkout: self
      submodules: recursive
    - template: templates/azure-pipelines/windows/pwsh/continuous-build.yml@PSModulePublisher
    - template: templates/azure-pipelines/windows/pwsh/publish.yml@PSModulePublisher
    - template: templates/azure-pipelines/run-release.yml@PSRepositoryReleaseManager
  - job: windows_powershell_5_0
    pool:
      vmImage: vs2015-win2012r2
    steps:
    - checkout: self
      submodules: recursive
    - template: templates/azure-pipelines/windows/powershell/continuous-build.yml@PSModulePublisher
    - template: templates/azure-pipelines/windows/powershell/publish.yml@PSModulePublisher
    - template: templates/azure-pipelines/run-release.yml@PSRepositoryReleaseManager
