trigger:
  branches:
    include:
      - '*'
  tags:
    include:
      - '*'
pr: none

resources:
  repositories:
    - repository: PSModulePublisher
      type: github
      name: theohbrothers/PSModulePublisher
      endpoint: joeltimothyoh
      ref: refs/tags/v0.0.3

stages:
- stage: Build_Test_Publish
  displayName: Build, Test, Publish
  jobs:
  - job: Windows
    pool:
      vmImage: windows-2019
    steps:
    - checkout: self
      submodules: true
    - template: azure-pipelines/windows/continuous-build.yml@PSModulePublisher
    - template: azure-pipelines/common/run-publish.yml@PSModulePublisher
