trigger:
  branches:
    include:
    - '*'
  tags:
    include:
    - '*'
pr: none
resources:
  repositories:
  - repository: PSModulePublisher
    type: github
    name: theohbrothers/PSModulePublisher
    endpoint: joeltimothyoh
    ref: refs/heads/dev
  - repository: PSRepositoryReleaseManager
    type: github
    name: theohbrothers/PSRepositoryReleaseManager
    endpoint: joeltimothyoh
    ref: refs/heads/dev

stages:
- stage: Build_Test_Publish
  displayName: Build, Test, Publish
  jobs:
  - job: Windows
    pool:
      vmImage: windows-2019
    steps:
    - checkout: self
      submodules: recursive
    - template: templates/azure-pipelines/windows/continuous-build.yml@PSModulePublisher
    - template: templates/azure-pipelines/common/run-publish.yml@PSModulePublisher
    - template: templates/azure-pipelines/run-release.yml@PSRepositoryReleaseManager
