trigger:
  branches:
    include:
    - 'master'
  tags:
    include:
    - '*'
pr:
  autoCancel: false
  branches:
    include:
    - '*'

# Ensure refs specified here matches those of submodules committed
resources:
  repositories:
  - repository: PSModulePublisher
    type: github
    name: theohbrothers/PSModulePublisher
    endpoint: joeltimothyoh
    ref: refs/tags/v0.4.0
  - repository: PSRepositoryReleaseManager
    type: github
    name: theohbrothers/PSRepositoryReleaseManager
    endpoint: joeltimothyoh
    ref: refs/tags/v0.7.0

variables:
  PUBLISH_DRY_RUN: false     # If true, Ensure to simulate with a tag version higher than the latest on PSGallery

stages:
- stage: build_test
  displayName: Build, Test
  condition: and(succeeded(), ne(variables['PUBLISH_DRY_RUN'], 'true'))
  jobs:
  - job: windows_pwsh
    displayName: '[Windows] PowerShell Core'
    pool:
      vmImage: windows-2022
    steps:
    - checkout: self
      submodules: recursive
    - template: templates/azure-pipelines/entrypoint/windows/continuous-build.yml@PSModulePublisher
  - job: windows_2019
    displayName: '[Windows Server 2019] PowerShell Core'
    pool:
      vmImage: windows-2019
    steps:
    - checkout: self
      submodules: recursive
    - template: templates/azure-pipelines/entrypoint/windows/continuous-build.yml@PSModulePublisher
  - job: windows_powershell_5_1
    displayName: '[Windows] PowerShell 5.1'
    pool:
      vmImage: windows-2022
    steps:
    - checkout: self
      submodules: recursive
    - template: templates/azure-pipelines/entrypoint/windows/powershell/continuous-build.yml@PSModulePublisher
  - job: windows_powershell_5_1_windows_2019
    displayName: '[Windows Server 2019] Windows PowerShell'
    pool:
      vmImage: windows-2019
    steps:
    - checkout: self
      submodules: recursive
    - template: templates/azure-pipelines/entrypoint/windows/powershell/continuous-build.yml@PSModulePublisher
  - job: linux
    displayName: '[Linux] PowerShell Core'
    pool:
      vmImage: ubuntu-22.04
    steps:
    - checkout: self
      submodules: recursive
    - template: templates/azure-pipelines/entrypoint/linux/continuous-build.yml@PSModulePublisher
  - job: linux_ubuntu_1804
    displayName: '[Linux Ubuntu 20.04] PowerShell Core'
    pool:
      vmImage: ubuntu-20.04
    steps:
    - checkout: self
      submodules: recursive
    - template: templates/azure-pipelines/entrypoint/linux/continuous-build.yml@PSModulePublisher
  - job: linux_container
    displayName: '[Linux] [Container] PowerShell'
    pool:
      vmImage: ubuntu-22.04
    strategy:
      matrix:
        7.0.0:
          containerImage: joeltimothyoh/powershell:7.0.0-ubuntu-18.04-git-sudo
        6.2.0:
          containerImage: joeltimothyoh/powershell:6.2.0-ubuntu-18.04-git-sudo
        6.1.0:
          containerImage: joeltimothyoh/powershell:6.1.0-ubuntu-18.04-git-sudo
    container: $[ variables['containerImage'] ]
    steps:
    - checkout: self
      submodules: recursive
    - template: templates/azure-pipelines/entrypoint/linux/continuous-build.yml@PSModulePublisher
  - job: linux_ubuntu_2004_container
    displayName: '[Linux Ubuntu 20.04] [Container] PowerShell'
    pool:
      vmImage: ubuntu-20.04
    strategy:
      matrix:
        7.0.0:
          containerImage: joeltimothyoh/powershell:7.0.0-ubuntu-18.04-git-sudo
        6.2.0:
          containerImage: joeltimothyoh/powershell:6.2.0-ubuntu-18.04-git-sudo
        6.1.0:
          containerImage: joeltimothyoh/powershell:6.1.0-ubuntu-18.04-git-sudo
    container: $[ variables['containerImage'] ]
    steps:
    - checkout: self
      submodules: recursive
    - template: templates/azure-pipelines/entrypoint/linux/continuous-build.yml@PSModulePublisher
  - job: macos
    displayName: '[macOS] PowerShell Core'
    pool:
      vmImage: macos-14
    steps:
    - checkout: self
      submodules: recursive
    - template: templates/azure-pipelines/entrypoint/macos/continuous-build.yml@PSModulePublisher
  - job: macos_1013
    displayName: '[macOS 13] PowerShell Core'
    pool:
      vmImage: macos-13
    steps:
    - checkout: self
      submodules: recursive
    - template: templates/azure-pipelines/entrypoint/macos/continuous-build.yml@PSModulePublisher

- stage: publish
  displayName: Publish
  dependsOn: build_test
  condition: and(succeeded(), ne(variables['PUBLISH_DRY_RUN'], 'true'))
  jobs:
  - job: windows_pwsh
    displayName: '[Windows] PowerShell Core'
    pool:
      vmImage: windows-2022
    steps:
    - checkout: self
      submodules: recursive
    - template: templates/azure-pipelines/entrypoint/windows/continuous-build.yml@PSModulePublisher
    - template: templates/azure-pipelines/entrypoint/windows/publish.yml@PSModulePublisher
  # - job: windows_powershell_5_1
  #   displayName: '[Windows] PowerShell 5.1'
  #   pool:
  #     vmImage: windows-2019
  #   steps:
  #   - checkout: self
  #     submodules: recursive
  #   - template: templates/azure-pipelines/entrypoint/windows/powershell/continuous-build.yml@PSModulePublisher
  #   - template: templates/azure-pipelines/entrypoint/windows/powershell/publish.yml@PSModulePublisher
  # - job: linux
  #   displayName: '[Linux] PowerShell Core'
  #   pool:
  #     vmImage: ubuntu-20.04
  #   steps:
  #   - checkout: self
  #     submodules: recursive
  #   - template: templates/azure-pipelines/entrypoint/linux/continuous-build.yml@PSModulePublisher
  #   - template: templates/azure-pipelines/entrypoint/linux/publish.yml@PSModulePublisher
  # - job: macos_1013
  #   displayName: '[macOS 13] PowerShell Core'
  #   pool:
  #     vmImage: macos-13
  #   steps:
  #   - checkout: self
  #     submodules: recursive
  #   - template: templates/azure-pipelines/entrypoint/macos/continuous-build.yml@PSModulePublisher
  #   - template: templates/azure-pipelines/entrypoint/macos/publish.yml@PSModulePublisher

- stage: release
  displayName: Release
  dependsOn: publish
  condition: and(succeeded(), ne(variables['PUBLISH_DRY_RUN'], 'true'))
  jobs:
  - job: linux_ubuntu_2204_container
    displayName: '[Linux Ubuntu 22.04] [Container] PowerShell 6.1.0'
    pool:
      vmImage: ubuntu-22.04
    container: joeltimothyoh/powershell:6.1.0-ubuntu-18.04-git
    steps:
    - checkout: self
      submodules: recursive
    - template: templates/azure-pipelines/entrypoint/generate.yml@PSRepositoryReleaseManager
    - template: templates/azure-pipelines/entrypoint/release.yml@PSRepositoryReleaseManager
  # - job: linux_ubuntu_2004
  #   displayName: '[Linux Ubuntu 20.04] PowerShell Core'
  #   pool:
  #     vmImage: ubuntu-20.04
  #   steps:
  #   - checkout: self
  #     submodules: recursive
  #   - template: templates/azure-pipelines/entrypoint/generate.yml@PSRepositoryReleaseManager
  #   - template: templates/azure-pipelines/entrypoint/release.yml@PSRepositoryReleaseManager

- stage: publish_dry_run
  displayName: Publish Dry Run
  dependsOn: []
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'), eq(variables['PUBLISH_DRY_RUN'], 'true'))
  jobs:
  - job: windows_pwsh
    displayName: '[Windows] PowerShell Core'
    pool:
      vmImage: windows-2022
    steps:
    - checkout: self
      submodules: recursive
    - template: templates/azure-pipelines/entrypoint/windows/continuous-build.yml@PSModulePublisher
    - template: templates/azure-pipelines/entrypoint/windows/publish.yml@PSModulePublisher
  - job: windows_powershell_5_1
    displayName: '[Windows] PowerShell 5.1'
    pool:
      vmImage: windows-2022
    steps:
    - checkout: self
      submodules: recursive
    - template: templates/azure-pipelines/entrypoint/windows/powershell/continuous-build.yml@PSModulePublisher
    - template: templates/azure-pipelines/entrypoint/windows/powershell/publish.yml@PSModulePublisher
  - job: windows_2019
    displayName: '[Windows Server 2019] Windows PowerShell'
    pool:
      vmImage: windows-2019
    steps:
    - checkout: self
      submodules: recursive
    - template: templates/azure-pipelines/entrypoint/windows/powershell/continuous-build.yml@PSModulePublisher
    - template: templates/azure-pipelines/entrypoint/windows/powershell/publish.yml@PSModulePublisher
  - job: linux
    displayName: '[Linux] PowerShell Core'
    pool:
      vmImage: ubuntu-22.04
    steps:
    - checkout: self
      submodules: recursive
    - template: templates/azure-pipelines/entrypoint/linux/continuous-build.yml@PSModulePublisher
    - template: templates/azure-pipelines/entrypoint/linux/publish.yml@PSModulePublisher
  - job: linux_ubuntu_1804
    displayName: '[Linux Ubuntu 20.04] PowerShell Core'
    pool:
      vmImage: ubuntu-20.04
    steps:
    - checkout: self
      submodules: recursive
    - template: templates/azure-pipelines/entrypoint/linux/continuous-build.yml@PSModulePublisher
    - template: templates/azure-pipelines/entrypoint/linux/publish.yml@PSModulePublisher
  # - job: linux_ubuntu_1804_container
  #   displayName: '[Linux Ubuntu 22.04] [Container] PowerShell'
  #   pool:
  #     vmImage: ubuntu-22.04
  #   strategy:
  #     matrix:
  #       7.0.0:
  #         containerImage: joeltimothyoh/powershell:7.0.0-ubuntu-18.04-git-sudo
  #       6.2.0:
  #         containerImage: joeltimothyoh/powershell:6.2.0-ubuntu-18.04-git-sudo
  #       6.1.0:
  #         containerImage: joeltimothyoh/powershell:6.1.0-ubuntu-18.04-git-sudo
  #   container: $[ variables['containerImage'] ]
  #   steps:
  #   - checkout: self
  #     submodules: recursive
  #   - template: templates/azure-pipelines/entrypoint/linux/continuous-build.yml@PSModulePublisher
  #   - template: templates/azure-pipelines/entrypoint/linux/publish.yml@PSModulePublisher
  - job: macos
    displayName: '[macOS] PowerShell Core'
    pool:
      vmImage: macos-14
    steps:
    - checkout: self
      submodules: recursive
    - template: templates/azure-pipelines/entrypoint/macos/continuous-build.yml@PSModulePublisher
    - template: templates/azure-pipelines/entrypoint/macos/publish.yml@PSModulePublisher
  - job: macos_1013
    displayName: '[macOS 13] PowerShell Core'
    pool:
      vmImage: macos-13
    steps:
    - checkout: self
      submodules: recursive
    - template: templates/azure-pipelines/entrypoint/macos/continuous-build.yml@PSModulePublisher
    - template: templates/azure-pipelines/entrypoint/macos/publish.yml@PSModulePublisher
